import { domains } from "@/domains";
import "@app/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function DomainsLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: {
		domain: string;
	};
}) {
	const { domain } = params;

	const domainData = domains.find((d) => d.name === domain);

	return (
		<html lang="en">
			<body
				className={inter.className}
				style={
					{
						"--theme-background": domainData?.theme.background,
						"--theme-textColor": domainData?.theme.textColor,
					} as React.CSSProperties
				}>
				{children}
			</body>
		</html>
	);
}
